language: node_js
node_js:
  - 12.10.0
beforinstall:
  - npm i -g firebase-tools
cache:
  directories:
    - node_modules
script:
  - yarn run build
deploy:
  provider: firebase
  project: demo-travis
  skip_cleanup: true
  token:
    secure: 1/RB38aWw6Dnd4Q0pIOPt6_3VB8WFd6xoqQZ42HF4boEQ
env:
  global:
  - secure: PmxYDMlDMe/bmEACFLodkF40ec6TbjRgad6Lc0nYICcdVGezoFI8u4WFLi6i4STW8y/doPJsboUGvtxpC6pHX+6alRx/2eZuSBYuXEMl2SlC+58W6ApGQVykWgNsUlN7QVbwXD2OKyntiVTU3p6sGqc0Nx2qsl1/zlOBfGMG9sG7FBfkYQ31MjKOmGkrSqpYeRy8UoyfVkE2tUdvLK0SAhuw5fu1Y9If2uCT2rsNVg/Uegmh1QTIOojiRwuFBfz3FFc0scjfbSdViicvOuJHUYTmO7gqzpuP+SVpsaCnBT5O8MBXR1mQqVzAunuY92BkfY7MK88JoRRHcD9L+ei5grzdNlvhH+5qerOOja3EGnUlQIqz0i/u8hwAzS/LVP4SO11WYR8fusKq4GPi1eyhtD23SHETY7whLYh2wAyowZqmsptZY81acRTzZk4axF2KxRS27Ut9b7F1mSpOfB+z1XcMNhlkuUg8dg9/aL0parSRezxsRaHNxIX2aaIm+Q4wQ6ydshyDcBePXrcmGh/tAsHhM6BXGhAD2xCNE5fhpahVGD6AqyKi5ajOrC8GDVa+Lil1PUObAtZF/+0NjqAcP7fTtnxZLa+GBCRyKDIkUgrEoYTObq4sl8rV1nj8zGYCj3fBiXSqMcSPzzEuNMPgZfF+e1T2X3EIpnoWCVOUPGQ=